version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
  "public/**,",
  "dist/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers.test-coverage.report_paths]]
path = "./coverage/lcov.info"
format = "lcov"