name: DeepSource Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the version of Node.js you are using in your project

      - name: Install dependencies
        run: npm install

      - name: Run Tests and Generate Coverage Report
        run: npm run coverage

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Run DeepSource Analysis
        env:
            DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file coverage/lcov.info
